export enum ChickenTalent {
  Anvil = "Anvil",
  BlackHole = "Black Hole",
  BlueEgg = "Blue Egg",
  BlueRooster = "Blue Rooster",
  Chickenapult = "Chickenapult",
  CK47 = "CK-47",
  ColdSnap = "Cold Snap",
  Coober = "Coober",
  Devolution = "Devolution",
  Dig = "Dig",
  FanGroup = "Fan Group",
  Flight = "Flight?",
  Growth = "Growth",
  Helicopter = "Helicopter",
  Jetpack = "Jetpack",
  Machete = "Machete",
  MovingWalkway = "Moving Walkway",
  Rollerblades = "Rollerblades",
  RoyalProcession = "Royal Procession",
  Teleport = "Teleport",
  FeatherRain = "Feather Rain",
  RunicRush = "Runic Rush",
}
